blank_issues_enabled: true
contact_links:
  - name: ğŸ‘‰ Problem with djLint? Open an issue here.
    url: https://github.com/djlint/djLint/issues
    about: Having a problem with djLint's formatting, linting, or other features?
